if("OpenMx" %in% rownames(installed.packages()) == FALSE) 
source('https://openmx.ssri.psu.edu/software/getOpenMx.R')
if("devtools" %in% rownames(installed.packages()) == FALSE) 
install.packages("devtools")
devtools::install("workingfunctions")