---
title: "Thurstonian IRT Example"
author: "Dimitrios Zacharatos"
output:
  html_document:
    css: styles.css
    toc: true
    toc_depth: 2
    theme: readable
vignette: >
  %\VignetteIndexEntry{Thurstonian IRT Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r options,echo=FALSE,warning=FALSE,message=FALSE}
options(width=1000)
hook_output <- function(x, options) {
  paste0('<pre class="r-output">', knitr::knit_print(x), '</pre>')
}
knitr::knit_hooks$set(output = hook_output)
knitr::opts_chunk$set(echo=TRUE)
options(future.show.progress = FALSE)
```

## Load

```{r library,message=FALSE,warning=FALSE}
library(thurstonianIRT)
```

## The data

First the data have to be encoded from Rank to binary.
Examples of encoding are shown bellow.

### Example 1

| Rank | Rank | Rank | 
|------|------|------|
| A    | B    | C    |
| 1    | 2    | 3    |

| binary | binary | binary | 
|--------|--------|--------|
| {A, B} | {A, C} | {B, C} |
|   1    |    1   |   1    |


### Example 2

| Rank | Rank | Rank | 
|------|------|------|
| A    | B    | C    |
| 2    | 1    | 3    |

| binary | binary | binary | 
|--------|--------|--------|
| {A, B} | {A, C} | {B, C} |
|   0    |    1   |   1    |

## The coded data

```{r load}
data("triplets")
head(triplets)
```

## Define blocks

```{r blocks}
blocks<-set_block(c("i1","i2","i3"),
                  traits=c("t1","t2","t3"),
                  signs=c(1,1,1))+
  set_block(c("i4","i5","i6"),
            traits=c("t1","t2","t3"),
            signs=c(-1,1,1))+
  set_block(c("i7","i8","i9"),
            traits=c("t1","t2","t3"),
            signs=c(1,1,-1))+
  set_block(c("i10","i11","i12"),
            traits=c("t1","t2","t3"),
            signs=c(1,-1,1))
print(data.frame(blocks[[1]]))
```

## Triplets

```{r triplets}
triplets_long<-make_TIRT_data(data=triplets,blocks=blocks,direction="larger",format="pairwise",family="bernoulli",range=c(0,1))
head(triplets_long)
```

## Model fit

```{r fit}
# fit_lavaan<-fit_TIRT_lavaan(triplets_long,control=list(maxiter=1000))
# fit_stan<-fit_TIRT_stan(triplets_long)
# save(fit_lavaan,fit_stan,file="fit.RData")
load("fit.RData")
print(fit_lavaan)
summary(fit_lavaan$fit)
model<-fit_lavaan$fit 

```

## Plot Model

```{r plot,fig.width=10,fig.height=10}
semPlot::semPaths(model,what="est",rotation=2,reorder=FALSE)
semPlot::semPaths(model,what="std",rotation=2,reorder=FALSE)
semPlot::semPaths(model,what="paths",rotation=2,reorder=FALSE)
```

## Evaluate Model
```{r evaluate}
# Fit indices
pt<-options(fit=c("GFI","AGFI","RMSEA","NFI","NNFI","CFI","RNI","IFI","SRMR","AIC","AICc","BIC","CAIC"))
fit_index<-data.frame(fit=lavaan::inspect(model,"fit",add.labels=TRUE,add.class=TRUE,list.by.group=TRUE,drop.list.single.group=TRUE))
round(fit_index,2)

# Explained variance
r_squared<-data.frame(r_squared=lavaan::inspect(model,"rsquare",add.labels=TRUE,add.class=TRUE,list.by.group=TRUE,drop.list.single.group=TRUE))
r_squared

# Estimates
unstandardized_estimates<-lavaan::inspect(model,"est",add.labels=TRUE,add.class=TRUE,list.by.group=TRUE,drop.list.single.group=TRUE)
unstandardized_estimates
standardized_estimates<-lavaan::inspect(model,"std",add.labels=TRUE,add.class=TRUE,list.by.group=TRUE,drop.list.single.group=TRUE)
standardized_estimates

lavaan::parameterEstimates(model,se=TRUE,
                           zstat=TRUE,
                           pvalue=TRUE,
                           ci=TRUE,
                           level=0.95,
                           boot.ci.type="perc",
                           standardized=TRUE,
                           fmi=FALSE,
                           remove.system.eq=TRUE,
                           remove.eq=FALSE,
                           remove.ineq=FALSE,
                           remove.def=FALSE,
                           rsquare=TRUE,
                           add.attributes=TRUE)
# Modification indices
lavaan::modificationIndices(model,
                            standardized=TRUE,
                            cov.std=TRUE,
                            information="expected",
                            power=TRUE,
                            delta=0.1,
                            alpha=0.05,
                            high.power=0.75,
                            sort.=TRUE,
                            minimum.value=0,
                            free.remove=FALSE,
                            na.remove=TRUE,
                            op=NULL)

```


## Score data

```{r score,message=FALSE}
score<-predict(fit_lavaan)
score<-data.frame(score)
score<-reshape(score, direction="wide", idvar="id", timevar="trait")

triplets_new<-make_TIRT_data(data=triplets[1,],blocks=blocks,direction="larger",format="pairwise",family="bernoulli",range=c(0,1))
score_new<-predict(fit_stan,newdata=triplets_new)
score_new<-data.frame(score_new)
score_new<-reshape(score_new[,c("id","trait","estimate")], direction="wide", idvar="id", timevar="trait")

```

## Print Scores

```{r score_new}

score

score_new

```










