---
title: "OCEAN Validation"
author: ""
output:
  html_document:
    css: styles.css
    toc: true
    toc_depth: 2
    theme: readable
  pdf_document:
    toc: true
    toc_depth: '2'
vignette: "%\\VignetteIndexEntry{OCEAN Validation} %\\VignetteEngine{knitr::rmarkdown} %\\VignetteEncoding{UTF-8}\n"
---

```{r options, echo=FALSE, warning=FALSE, message=FALSE}
options(width=1000)
hook_output <- function(x, options) {
  paste0('<pre class="r-output">', knitr::knit_print(x), '</pre>')
}
knitr::knit_hooks$set(output = hook_output)
knitr::opts_chunk$set(echo=TRUE)
options(future.show.progress = FALSE)
```

```{r load, include=FALSE}
library(rwf)
library(psych)
library(ggplot2)
library(reshape2)

data(df_ocean)

# Item columns only
item_cols <- c(paste0("E", 1:10), paste0("N", 1:10),
               paste0("A", 1:10), paste0("C", 1:10), paste0("O", 1:10))

# Reverse-scored items (IPIP-50 scoring key, 5 - x on 0-5 scale)
reverse_items <- c("E2","E4","E6","E8","E10",
                   "N2","N4",
                   "A1","A3","A5","A7",
                   "C2","C4","C6","C8",
                   "O2","O4","O6")

df <- df_ocean[, item_cols]
for (v in reverse_items) df[[v]] <- 5 - df[[v]]

# Rename columns: keep dimension prefix, add R for reverse items
# e.g. E1, E2R, E3, E4R ...
new_names <- ifelse(item_cols %in% reverse_items,
                    paste0(item_cols, "R"),
                    item_cols)
colnames(df) <- new_names

# Factor groupings using new names
factors <- list(
  Extraversion      = new_names[1:10],
  Neuroticism       = new_names[11:20],
  Agreeableness     = new_names[21:30],
  Conscientiousness = new_names[31:40],
  Openness          = new_names[41:50]
)

factor_order <- unlist(factors)
item_labels  <- unlist(lapply(names(factors), function(f) rep(f, 10)))
names(item_labels) <- factor_order

```


## Inter-Item Correlation Matrix

```{r corrmatrix, fig.width=10, fig.height=9, echo=TRUE, message=FALSE, warning=FALSE, results='show', dev='png', fig.retina=2}
cor_mat  <- cor(df[, factor_order], use = "pairwise.complete.obs")
cor_long <- melt(cor_mat)
cor_long$Var1 <- factor(cor_long$Var1, levels = factor_order)
cor_long$Var2 <- factor(cor_long$Var2, levels = factor_order)

p_cor <- ggplot(cor_long, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile(color = "white", linewidth = 0.2) +
  scale_fill_gradient2(low = "#2166ac", mid = "white", high = "#d6604d",
                       midpoint = 0, limits = c(-1, 1), name = "r") +
  theme_bw(base_size = 9) +
  theme(axis.text.x  = element_text(angle = 90, hjust = 1, size = 7),
        axis.text.y  = element_text(size = 7),
        axis.title   = element_blank(),
        panel.grid   = element_blank()) +
  ggtitle("IPIP-50 inter-item correlation matrix\nItems ordered by dimension; R = reverse-scored (already recoded)")

print(p_cor)
```

## Exploratory Factor Analysis (5 Factors)

```{r efa, fig.width=7, fig.height=10, echo=TRUE, message=FALSE, warning=FALSE, results='show', dev='png', fig.retina=2}
set.seed(42)
efa <- fa(df, nfactors = 5, rotate = "oblimin", fm = "ml", scores = "regression")

print(efa$loadings, cutoff = 0.30, sort = TRUE)

loadings_mat           <- as.data.frame(unclass(efa$loadings))
colnames(loadings_mat) <- paste0("F", 1:5)
loadings_mat$item      <- rownames(loadings_mat)
loadings_mat$expected  <- item_labels[loadings_mat$item]

load_long      <- melt(loadings_mat, id.vars = c("item", "expected"),
                       variable.name = "factor", value.name = "loading")
load_long$item <- factor(load_long$item, levels = factor_order)

p_load <- ggplot(load_long, aes(x = factor, y = item, fill = loading)) +
  geom_tile(color = "white", linewidth = 0.3) +
  geom_text(aes(label = ifelse(abs(loading) >= 0.30, round(loading, 2), "")),
            size = 2.5) +
  scale_fill_gradient2(low = "#2166ac", mid = "white", high = "#d6604d",
                       midpoint = 0, limits = c(-1, 1), name = "loading") +
  facet_grid(expected ~ ., scales = "free_y", space = "free_y") +
  theme_bw(base_size = 9) +
  theme(strip.text.y = element_text(angle = 0, size = 8),
        axis.text.y  = element_text(size = 7),
        axis.title   = element_blank(),
        panel.grid   = element_blank()) +
  ggtitle("EFA factor loadings (oblimin rotation, 5 factors)\nValues >= |0.30| shown; R = reverse-scored item")

print(p_load)
```

## Parallel Analysis

```{r parallel, fig.width=8, fig.height=5, echo=TRUE, message=FALSE, warning=FALSE, results='show', dev='png', fig.retina=2}
fa.parallel(df, fm="ml", fa="fa",
            main="Parallel analysis scree plot (BFI-44)")
```
