#' Admission Data
#'
#' This data set contains information about graduate admission, 
#' including GRE scores, GPA, and the ranking of the undergraduate institution.
#'
#' @format A data frame with 8 rows and 4 variables:
#' \describe{
#'   \item{admit}{Binary variable indicating admission (0=No, 1=Yes)}
#'   \item{gre}{GRE (Graduate Record Examination) score}
#'   \item{gpa}{Grade Point Average}
#'   \item{rank}{Ranking of the undergraduate institution (1=highest, 4=lowest)}
#' }
#' @source researchpy repo
"df_admission"

#' Automotive Data
#'
#' This data set contains various automotive information including 
#' engine location, dimensions, weight, engine type, number of cylinders, 
#' and other specifications.
#'
#' @format A data frame with 38 rows and 26 variables:
#' \describe{
#'   \item{symboling}{Symboling code for the vehicle}
#'   \item{normalized-losses}{Normalized losses in the vehicle}
#'   \item{make}{Make of the vehicle}
#'   \item{fuel-type}{Type of fuel used (e.g., gas, diesel)}
#'   \item{aspiration}{Aspiration type (e.g., std, turbo)}
#'   \item{num-of-doors}{Number of doors (e.g., two, four)}
#'   \item{body-style}{Body style (e.g., sedan, hatchback, wagon)}
#'   \item{drive-wheels}{Drive wheels (e.g., fwd, rwd, 4wd)}
#'   \item{engine-location}{Location of the engine (e.g., front, rear)}
#'   \item{wheel-base}{Wheelbase of the vehicle in inches}
#'   \item{length}{Length of the vehicle in inches}
#'   \item{width}{Width of the vehicle in inches}
#'   \item{height}{Height of the vehicle in inches}
#'   \item{curb-weight}{Curb weight of the vehicle in pounds}
#'   \item{engine-type}{Type of engine (e.g., dohc, ohcv, ohc, l)}
#'   \item{num-of-cylinders}{Number of cylinders in the engine}
#'   \item{engine-size}{Size of the engine in cubic inches}
#'   \item{fuel-system}{Fuel system used (e.g., mpfi, 2bbl, mfi, 1bbl)}
#'   \item{bore}{Diameter of the cylinders in the engine}
#'   \item{stroke}{Stroke length of the engine}
#'   \item{compression-ratio}{Compression ratio of the engine}
#'   \item{horsepower}{Horsepower generated by the engine}
#'   \item{peak-rpm}{Peak RPM of the engine}
#'   \item{city-mpg}{Miles per gallon in the city}
#'   \item{highway-mpg}{Miles per gallon on the highway}
#'   \item{price}{Price of the vehicle}
#'   }
#' @source Downloaded from Kaggle.com by the user Ramakrishnan Srinivasan. 
#' see \url{https://www.kaggle.com/toramky/automobile-dataset}
"df_automotive_data"

#' Blood Pressure Data
#'
#' This data set contains blood pressure readings for patients before and after a certain treatment or intervention.
#'
#' @format A data frame with 30 rows and 5 variables:
#' \describe{
#'   \item{patient}{Unique identifier for each patient}
#'   \item{sex}{Sex of the patient (e.g., Male, Female)}
#'   \item{agegrp}{Age group of the patient (e.g., 30-45, 46-59)}
#'   \item{bp_before}{Blood pressure reading before the intervention}
#'   \item{bp_after}{Blood pressure reading after the intervention}
#' }
#' @source researchpy repo
"df_blood_pressure"

#' Crop Yield Data
#'
#' This data set contains information about crop yields based on different fertilizer types and water conditions.
#'
#' @format A data frame with 20 rows and 3 variables:
#' \describe{
#'   \item{Fert}{Type of fertilizer used (A or B)}
#'   \item{Water}{Watering condition (High or Low)}
#'   \item{Yield}{Crop yield (in unspecified units)}
#' }
#' @source researchpy repo (simulated data, not real)
"df_crop_yield"

#' Difficile Data
#'
#' This data set contains information about the impact of different doses on libido.
#'
#' @format A data frame with 15 rows and 3 variables:
#' \describe{
#'   \item{person}{Unique identifier for each person}
#'   \item{dose}{Dose received (e.g., 1, 2, 3)}
#'   \item{libido}{Libido level of the person}
#' }
#' @source researchpy repo
"df_difficile"

#' Insurance Data
#'
#' This data set contains information about insurance charges based on various factors 
#' such as age, sex, BMI, number of children, smoking status, and region.
#'
#' @format A data frame with 19 rows and 7 variables:
#' \describe{
#'   \item{age}{Age of the individual}
#'   \item{sex}{Sex of the individual (e.g., male, female)}
#'   \item{bmi}{Body Mass Index of the individual}
#'   \item{children}{Number of children covered by the insurance}
#'   \item{smoker}{Smoking status (yes or no)}
#'   \item{region}{Region where the individual resides (e.g., southwest, southeast, northwest, northeast)}
#'   \item{charges}{Insurance charges}
#' }
#' @source researchpy repo
"df_insurance"

#' Responses State Data
#'
#' This data set contains simulated state information paired with participant numbers from the responses data set.
#'
#' @format A data frame with 28 rows and 2 variables:
#' \describe{
#'   \item{Participant Number}{Unique identifier for each participant}
#'   \item{State}{State code where the participant resides (e.g., MI, OH, CO, CA, MA, WA)}
#' }
#' @source researchpy repo (simulated data, not real)
"df_responses_state"

#' Sexual Compatibility Data
#'
#' This data set contains responses to questions about sexual compatibility, 
#' including scores, gender, and age.
#'
#' @format A data frame with 22 rows and 13 variables:
#' \describe{
#'   \item{Q1}{Response to question 1}
#'   \item{Q2}{Response to question 2}
#'   \item{Q3}{Response to question 3}
#'   \item{Q4}{Response to question 4}
#'   \item{Q5}{Response to question 5}
#'   \item{Q6}{Response to question 6}
#'   \item{Q7}{Response to question 7}
#'   \item{Q8}{Response to question 8}
#'   \item{Q9}{Response to question 9}
#'   \item{Q10}{Response to question 10}
#'   \item{score}{Total score}
#'   \item{gender}{Gender of the respondent (1=Male, 2=Female)}
#'   \item{age}{Age of the respondent}
#' }
#' @source researchpy repo
"df_sexual_comp"

#' Personality Dataset
#'
#' A dataset containing personality test results.
#'
#' @format A data frame with 22 rows and 44 variables:
#' \describe{
#'   \item{pers01}{Personality item 1}
#'   \item{pers02}{Personality item 2}
#'   \item{pers03}{Personality item 3}
#'   \item{pers04}{Personality item 4}
#'   \item{pers05}{Personality item 5}
#'   \item{pers06}{Personality item 6}
#'   \item{pers07}{Personality item 7}
#'   \item{pers08}{Personality item 8}
#'   \item{pers09}{Personality item 9}
#'   \item{pers10}{Personality item 10}
#'   \item{pers11}{Personality item 11}
#'   \item{pers12}{Personality item 12}
#'   \item{pers13}{Personality item 13}
#'   \item{pers14}{Personality item 14}
#'   \item{pers15}{Personality item 15}
#'   \item{pers16}{Personality item 16}
#'   \item{pers17}{Personality item 17}
#'   \item{pers18}{Personality item 18}
#'   \item{pers19}{Personality item 19}
#'   \item{pers20}{Personality item 20}
#'   \item{pers21}{Personality item 21}
#'   \item{pers22}{Personality item 22}
#'   \item{pers23}{Personality item 23}
#'   \item{pers24}{Personality item 24}
#'   \item{pers25}{Personality item 25}
#'   \item{pers26}{Personality item 26}
#'   \item{pers27}{Personality item 27}
#'   \item{pers28}{Personality item 28}
#'   \item{pers29}{Personality item 29}
#'   \item{pers30}{Personality item 30}
#'   \item{pers31}{Personality item 31}
#'   \item{pers32}{Personality item 32}
#'   \item{pers33}{Personality item 33}
#'   \item{pers34}{Personality item 34}
#'   \item{pers35}{Personality item 35}
#'   \item{pers36}{Personality item 36}
#'   \item{pers37}{Personality item 37}
#'   \item{pers38}{Personality item 38}
#'   \item{pers39}{Personality item 39}
#'   \item{pers40}{Personality item 40}
#'   \item{pers41}{Personality item 41}
#'   \item{pers42}{Personality item 42}
#'   \item{pers43}{Personality item 43}
#'   \item{pers44}{Personality item 44}
#' }
#' @examples
#' data(df_personality)
#' head(df_personality)
"df_personality"

#' Titanic Dataset
#'
#' A dataset containing information about passengers on the Titanic.
#'
#' @format A data frame with the following variables:
#' \describe{
#'   \item{PassengerId}{Unique identifier for each passenger}
#'   \item{survived}{Survival status (0=No, 1=Yes)}
#'   \item{pclass}{Passenger class (1=1st, 2=2nd, 3=3rd)}
#'   \item{name}{Name of the passenger}
#'   \item{sex}{Gender of the passenger}
#'   \item{age}{Age of the passenger}
#'   \item{sibsp}{Number of siblings/spouses aboard the Titanic}
#'   \item{parch}{Number of parents/children aboard the Titanic}
#'   \item{ticket}{Ticket number}
#'   \item{fare}{Passenger fare}
#'   \item{cabin}{Cabin number}
#'   \item{embarked}{Port of embarkation (C=Cherbourg; Q=Queenstown; S=Southampton)}
#'   \item{boat}{Lifeboat number}
#'   \item{body}{Body number}
#'   \item{home.dest}{Home destination}
#' }
#' @examples
#' data(df_titanic)
#' head(df_titanic)
"df_titanic"

#' Carbon Dioxide Uptake in Grass Plants
#'
#' The CO2 data frame has 84 rows and 5 columns of data from an experiment on the cold tolerance of the grass species Echinochloa crus-galli.
#'
#' @format A data frame with 84 rows and 5 variables:
#' \describe{
#'   \item{Plant}{an ordered factor with levels Qn1 < Qn2 < Qn3 < ... < Mc1 giving a unique identifier for each plant). Used as a grouping factor.}
#'   \item{Type}{a factor with levels Quebec Mississippi giving the origin of the plant}
#'   \item{Treatment}{a factor with levels nonchilled chilled}
#'   \item{conc}{a numeric vector of ambient carbon dioxide concentrations (mL/L)}
#'   \item{uptake}{a numeric vector of carbon dioxide uptake rates (in \eqn{\mu}mol/m²/sec)}
#' }
#'
#' @details
#' Grouped formulas like \code{uptake ~ conc | Plant} are useful in lattice graphics
#' and mixed-effect models. The vertical bar (`|`) separates the grouping variable.
#' This allows modeling or plotting the response (\code{uptake}) versus the predictor
#' (\code{conc}) within each level of \code{Plant}.
#' 
#' @source
#' Potvin, C., Lechowicz, M. J. and Tardif, S. (1990) “The statistical analysis of ecophysiological response curves obtained from experiments involving repeated measures”, Ecology, 71, 1389–1400.
#' Pinheiro, J. C. and Bates, D. M. (2000) Mixed-effects Models in S and S-PLUS, Springer.
#' @examples
#' data(df_co2)
#' head(df_co2)

"df_co2"

#' Big Five Personality Test Dataset
#'
#' This dataset contains responses to an interactive online Big Five personality test
#' conducted around 2012. Participants rated themselves on 50 personality statements,
#' and also provided demographic and technical metadata. Responses were collected
#' with informed consent, and missing data is coded as 0.
#'
#' @format A data frame with 19719 rows and 57 variables:
#' \describe{
#'   \item{E1}{I am the life of the party.}
#'   \item{E2}{I don't talk a lot.}
#'   \item{E3}{I feel comfortable around people.}
#'   \item{E4}{I keep in the background.}
#'   \item{E5}{I start conversations.}
#'   \item{E6}{I have little to say.}
#'   \item{E7}{I talk to a lot of different people at parties.}
#'   \item{E8}{I don't like to draw attention to myself.}
#'   \item{E9}{I don't mind being the center of attention.}
#'   \item{E10}{I am quiet around strangers.}
#'   \item{N1}{I get stressed out easily.}
#'   \item{N2}{I am relaxed most of the time.}
#'   \item{N3}{I worry about things.}
#'   \item{N4}{I seldom feel blue.}
#'   \item{N5}{I am easily disturbed.}
#'   \item{N6}{I get upset easily.}
#'   \item{N7}{I change my mood a lot.}
#'   \item{N8}{I have frequent mood swings.}
#'   \item{N9}{I get irritated easily.}
#'   \item{N10}{I often feel blue.}
#'   \item{A1}{I feel little concern for others.}
#'   \item{A2}{I am interested in people.}
#'   \item{A3}{I insult people.}
#'   \item{A4}{I sympathize with others' feelings.}
#'   \item{A5}{I am not interested in other people's problems.}
#'   \item{A6}{I have a soft heart.}
#'   \item{A7}{I am not really interested in others.}
#'   \item{A8}{I take time out for others.}
#'   \item{A9}{I feel others' emotions.}
#'   \item{A10}{I make people feel at ease.}
#'   \item{C1}{I am always prepared.}
#'   \item{C2}{I leave my belongings around.}
#'   \item{C3}{I pay attention to details.}
#'   \item{C4}{I make a mess of things.}
#'   \item{C5}{I get chores done right away.}
#'   \item{C6}{I often forget to put things back in their proper place.}
#'   \item{C7}{I like order.}
#'   \item{C8}{I shirk my duties.}
#'   \item{C9}{I follow a schedule.}
#'   \item{C10}{I am exacting in my work.}
#'   \item{O1}{I have a rich vocabulary.}
#'   \item{O2}{I have difficulty understanding abstract ideas.}
#'   \item{O3}{I have a vivid imagination.}
#'   \item{O4}{I am not interested in abstract ideas.}
#'   \item{O5}{I have excellent ideas.}
#'   \item{O6}{I do not have a good imagination.}
#'   \item{O7}{I am quick to understand things.}
#'   \item{O8}{I use difficult words.}
#'   \item{O9}{I spend time reflecting on things.}
#'   \item{O10}{I am full of ideas.}
#'   \item{E1 to E10}{Extraversion items}
#'   \item{N1 to N10}{Neuroticism items}
#'   \item{A1 to A10}{Agreeableness items}
#'   \item{C1 to C10}{Conscientiousness items}
#'   \item{O1 to O10}{Openness to experience items}
#'   \item{race}{Race/ethnic background (1–13, 0=missing)}
#'   \item{age}{Age (integer; only responses from participants 13 and older included)}
#'   \item{engnat}{Is English your native language? (1=Yes, 2=No, 0=missing)}
#'   \item{gender}{1=Male, 2=Female, 3=Other, 0=missing}
#'   \item{hand}{Dominant writing hand: 1=Right, 2=Left, 3=Both, 0=missing}
#'   \item{country}{Two-letter ISO country code (e.g., "US", "GB")}
#'   \item{source}{How participant came to the test site: 
#'     1=Internal link,
#'     2=Google,
#'     3=Facebook,
#'     4=.edu site,
#'     6=Other/unknown}
#' }
#'
#' @details
#' Personality items were rated on a five-point Likert scale: #' 1=Disagree, 3=Neutral, 5=Agree. Missed=0.
#' 
#' \strong{race} Chosen from a drop down menu. 1=Mixed Race, 2=Arctic (Siberian, Eskimo), 3=Caucasian (European), 4=Caucasian (Indian), 5=Caucasian (Middle East), 6=Caucasian (North African, Other), 7=Indigenous Australian, 8=Native American, 9=North East Asian (Mongol, Tibetan, Korean Japanese, etc), 10=Pacific (Polynesian, Micronesian, etc), 11=South East Asian (Chinese, Thai, Malay, Filipino, etc), 12=West African, Bushmen, Ethiopian, 13=Other (0=missed)
#' 
#' \strong{age}	Entered as text (individuals reporting age < 13 were not recorded)
#' 
#' \strong{engnat}	Response to "is English your native language?". 1=Yes, 2=No (0=missed)
#' 
#' \strong{gender}	Chosen from a drop down menu. 1=Male, 2=Female, 3=Other (0=missed)
#' 
#' \strong{hand}	"What hand do you use to write with?". 1=Right, 2=Left, 3=Both (0=missed)
#' 
#' On this page users were also asked to confirm that their answers were accurate and could be used for research. Participants who did not were not recorded). Some values were calculated from technical information.
#' 
#' \strong{country}	The participant's technical location. ISO country code.
#' 
#' \strong{source}	How the participant came to the test. Based on HTTP Referrer. 1=from another page on the test website, 2=from google, 3=from facebook, 4=from any url with ".edu" in its domain name (e.g. xxx.edu, xxx.edu.au), 6=other source, or HTTP Referer not provided.
#' 
#' In psychological trait theory, the Big Five personality traits, also known as the five-factor model (FFM) and the OCEAN model, is a suggested taxonomy, or grouping, for personality traits, developed from the 1980s onwards. When factor analysis (a statistical technique) is applied to personality survey data, some words used to describe aspects of personality are often applied to the same person. For example, someone described as conscientious is more likely to be described as "always prepared" rather than "messy". This theory is based therefore on semantic associations between words and not on neuropsychological experiments. This theory uses descriptors of common language and suggests five broad dimensions commonly used to describe the human personality and psyche.
#' 
#' The theory identifies five factors:
#' \itemize{
#'   \item \strong{Openness to experience (O)} (inventive/curious vs. consistent/cautious)
#'   \item \strong{Conscientiousness (C)} (efficient/organized vs. extravagant/careless)
#'   \item \strong{Extraversion (E)} (outgoing/energetic vs. solitary/reserved)
#'   \item \strong{Agreeableness (A)} (friendly/compassionate vs. challenging/callous)
#'   \item \strong{Neuroticism (N)} (sensitive/nervous vs. resilient/confident)
#' }
#' The five factors are represented using the acronyms OCEAN or CANOE. Beneath each proposed global factor, there are a number of correlated and more specific primary factors. For example, extroversion is typically associated with qualities such as gregariousness, assertiveness, excitement-seeking, warmth, activity, and positive emotions.  
#' Family life and the way someone was raised will affect these traits. Twin studies and other research have shown that about half of the variation between individuals results from their genetics and half from their environments. Researchers have found conscientiousness, extroversion, openness to experience, and neuroticism to be relatively stable from childhood through adulthood.
#' 
#' Items are grouped by Big Five traits:
#' \itemize{
#'   \item \strong{Extraversion (E)}: E1 to E10
#'   \item \strong{Neuroticism (N)}: N1 to N10
#'   \item \strong{Agreeableness (A)}: A1 to A10
#'   \item \strong{Conscientiousness (C)}: C1 to C10
#'   \item \strong{Openness (O)}: O1 to O10
#' }
#'
#' Negatively keyed items are: E2, E4, E6, E8, E10, N2, N4, A1, A3, A5, A7, C2, C4, C6, C8, O2, O4, O6.
#' These should be reverse-coded prior to scoring.
#'
#' @source
#' Collected via an online personality test with informed consent (~2012).
#' Downloaded from Kaggle.com by the user Lucas Greenwell. see \url{https://www.kaggle.com/datasets/lucasgreenwell/ocean-five-factor-personality-test-responses}
#' 
#' @examples
#' data(bfi_data)
#' head(bfi_data)
#' 
#' # Compute Big Five average scores (after reverse scoring)
#' # library(dplyr)
#' # bfi_data <- bfi_data %>% mutate(E=rowMeans(select(., E1:E10), na.rm=TRUE))
#'
"df_ocean"

