#' Admission Data
#'
#' This data set contains information about graduate admission, 
#' including GRE scores, GPA, and the ranking of the undergraduate institution.
#'
#' @format A data frame with 8 rows and 4 variables:
#' \describe{
#'   \item{admit}{Binary variable indicating admission (0=No, 1=Yes)}
#'   \item{gre}{GRE (Graduate Record Examination) score}
#'   \item{gpa}{Grade Point Average}
#'   \item{rank}{Ranking of the undergraduate institution (1=highest, 4=lowest)}
#' }
#' @source researchpy repo
"df_admission"

#' Automotive Data
#'
#' This data set contains various automotive information including 
#' engine location, dimensions, weight, engine type, number of cylinders, 
#' and other specifications.
#'
#' @format A data frame with 38 rows and 26 variables:
#' \describe{
#'   \item{symboling}{Symboling code for the vehicle}
#'   \item{normalized-losses}{Normalized losses in the vehicle}
#'   \item{make}{Make of the vehicle}
#'   \item{fuel-type}{Type of fuel used (e.g., gas, diesel)}
#'   \item{aspiration}{Aspiration type (e.g., std, turbo)}
#'   \item{num-of-doors}{Number of doors (e.g., two, four)}
#'   \item{body-style}{Body style (e.g., sedan, hatchback, wagon)}
#'   \item{drive-wheels}{Drive wheels (e.g., fwd, rwd, 4wd)}
#'   \item{engine-location}{Location of the engine (e.g., front, rear)}
#'   \item{wheel-base}{Wheelbase of the vehicle in inches}
#'   \item{length}{Length of the vehicle in inches}
#'   \item{width}{Width of the vehicle in inches}
#'   \item{height}{Height of the vehicle in inches}
#'   \item{curb-weight}{Curb weight of the vehicle in pounds}
#'   \item{engine-type}{Type of engine (e.g., dohc, ohcv, ohc, l)}
#'   \item{num-of-cylinders}{Number of cylinders in the engine}
#'   \item{engine-size}{Size of the engine in cubic inches}
#'   \item{fuel-system}{Fuel system used (e.g., mpfi, 2bbl, mfi, 1bbl)}
#'   \item{bore}{Diameter of the cylinders in the engine}
#'   \item{stroke}{Stroke length of the engine}
#'   \item{compression-ratio}{Compression ratio of the engine}
#'   \item{horsepower}{Horsepower generated by the engine}
#'   \item{peak-rpm}{Peak RPM of the engine}
#'   \item{city-mpg}{Miles per gallon in the city}
#'   \item{highway-mpg}{Miles per gallon on the highway}
#'   \item{price}{Price of the vehicle}
#'   }
#' @source Downloaded from Kaggle.com by the user Ramakrishnan Srinivasan. 
#' see \url{https://www.kaggle.com/toramky/automobile-dataset}
"df_automotive_data"

#' Blood Pressure Data
#'
#' This data set contains blood pressure readings for patients before and after a certain treatment or intervention.
#'
#' @format A data frame with 30 rows and 5 variables:
#' \describe{
#'   \item{patient}{Unique identifier for each patient}
#'   \item{sex}{Sex of the patient (e.g., Male, Female)}
#'   \item{agegrp}{Age group of the patient (e.g., 30-45, 46-59)}
#'   \item{bp_before}{Blood pressure reading before the intervention}
#'   \item{bp_after}{Blood pressure reading after the intervention}
#' }
#' @source researchpy repo
"df_blood_pressure"

#' Crop Yield Data
#'
#' This data set contains information about crop yields based on different fertilizer types and water conditions.
#'
#' @format A data frame with 20 rows and 3 variables:
#' \describe{
#'   \item{Fert}{Type of fertilizer used (A or B)}
#'   \item{Water}{Watering condition (High or Low)}
#'   \item{Yield}{Crop yield (in unspecified units)}
#' }
#' @source researchpy repo (simulated data, not real)
"df_crop_yield"

#' Difficile Data
#'
#' This data set contains information about the impact of different doses on libido.
#'
#' @format A data frame with 15 rows and 3 variables:
#' \describe{
#'   \item{person}{Unique identifier for each person}
#'   \item{dose}{Dose received (e.g., 1, 2, 3)}
#'   \item{libido}{Libido level of the person}
#' }
#' @source researchpy repo
"df_difficile"

#' Insurance Data
#'
#' This data set contains information about insurance charges based on various factors 
#' such as age, sex, BMI, number of children, smoking status, and region.
#'
#' @format A data frame with 19 rows and 7 variables:
#' \describe{
#'   \item{age}{Age of the individual}
#'   \item{sex}{Sex of the individual (e.g., male, female)}
#'   \item{bmi}{Body Mass Index of the individual}
#'   \item{children}{Number of children covered by the insurance}
#'   \item{smoker}{Smoking status (yes or no)}
#'   \item{region}{Region where the individual resides (e.g., southwest, southeast, northwest, northeast)}
#'   \item{charges}{Insurance charges}
#' }
#' @source researchpy repo
"df_insurance"

#' Responses State Data
#'
#' This data set contains simulated state information paired with participant numbers from the responses data set.
#'
#' @format A data frame with 28 rows and 2 variables:
#' \describe{
#'   \item{Participant Number}{Unique identifier for each participant}
#'   \item{State}{State code where the participant resides (e.g., MI, OH, CO, CA, MA, WA)}
#' }
#' @source researchpy repo (simulated data, not real)
"df_responses_state"

#' Sexual Compatibility Data
#'
#' Responses from 3,376 participants to a 10-item sexual compatibility
#' questionnaire. The dataset is used as a teaching example in the researchpy
#' Python statistics tutorials. The exact item wording is not publicly
#' documented by the original source.
#'
#' @format A data frame with 3376 rows and 13 variables. Each of Q1-Q10 is
#'   rated on a 0-4 scale; \code{score} is the unweighted sum (range 0-40).
#'   Note: age value 999 is a missing-data code; gender codes 0 and 3 are
#'   rare and likely represent missing or other responses.
#' \describe{
#'   \item{Q1}{Sexual compatibility item 1 (0-4)}
#'   \item{Q2}{Sexual compatibility item 2 (0-4)}
#'   \item{Q3}{Sexual compatibility item 3 (0-4)}
#'   \item{Q4}{Sexual compatibility item 4 (0-4)}
#'   \item{Q5}{Sexual compatibility item 5 (0-4)}
#'   \item{Q6}{Sexual compatibility item 6 (0-4)}
#'   \item{Q7}{Sexual compatibility item 7 (0-4)}
#'   \item{Q8}{Sexual compatibility item 8 (0-4)}
#'   \item{Q9}{Sexual compatibility item 9 (0-4)}
#'   \item{Q10}{Sexual compatibility item 10 (0-4)}
#'   \item{score}{Total scale score (sum of Q1-Q10, range 0-40)}
#'   \item{gender}{Gender (1=Male, 2=Female; 0 and 3 = missing/other)}
#'   \item{age}{Age in years (999 = missing)}
#' }
#' @source researchpy Data-sets repository (\url{https://github.com/researchpy/Data-sets})
"df_sexual_comp"

#' Big Five Inventory (BFI-44) Personality Dataset
#'
#' Responses from 433 participants to the Big Five Inventory (BFI-44), a
#' widely used measure of the five major dimensions of personality: Extraversion
#' (E), Agreeableness (A), Conscientiousness (C), Neuroticism (N), and Openness
#' to Experience (O). Items are rated on a 1-6 Likert scale. Reverse-scored
#' items are marked with (R).
#'
#' @format A data frame with 433 rows and 44 variables:
#' \describe{
#'   \item{pers01}{[E] Is talkative}
#'   \item{pers02}{[A-R] Tends to find fault with others}
#'   \item{pers03}{[C] Does a thorough job}
#'   \item{pers04}{[N] Is depressed, blue}
#'   \item{pers05}{[O] Is original, comes up with new ideas}
#'   \item{pers06}{[E-R] Is reserved}
#'   \item{pers07}{[A] Is helpful and unselfish with others}
#'   \item{pers08}{[C-R] Can be somewhat careless}
#'   \item{pers09}{[N-R] Is relaxed, handles stress well}
#'   \item{pers10}{[O] Is curious about many different things}
#'   \item{pers11}{[E] Is full of energy}
#'   \item{pers12}{[A-R] Starts quarrels with others}
#'   \item{pers13}{[C] Is a reliable worker}
#'   \item{pers14}{[N] Can be tense}
#'   \item{pers15}{[O] Is ingenious, a deep thinker}
#'   \item{pers16}{[E] Generates a lot of enthusiasm}
#'   \item{pers17}{[A] Has a forgiving nature}
#'   \item{pers18}{[C-R] Tends to be disorganized}
#'   \item{pers19}{[N] Worries a lot}
#'   \item{pers20}{[O] Has an active imagination}
#'   \item{pers21}{[E-R] Tends to be quiet}
#'   \item{pers22}{[A] Is generally trusting}
#'   \item{pers23}{[C-R] Tends to be lazy}
#'   \item{pers24}{[N-R] Is emotionally stable, not easily upset}
#'   \item{pers25}{[O] Is inventive}
#'   \item{pers26}{[E] Has an assertive personality}
#'   \item{pers27}{[A-R] Can be cold and aloof}
#'   \item{pers28}{[C] Perseveres until the task is finished}
#'   \item{pers29}{[N] Can be moody}
#'   \item{pers30}{[O] Values artistic, aesthetic experiences}
#'   \item{pers31}{[E-R] Is sometimes shy, inhibited}
#'   \item{pers32}{[A] Is considerate and kind to almost everyone}
#'   \item{pers33}{[C] Does things efficiently}
#'   \item{pers34}{[N-R] Remains calm in tense situations}
#'   \item{pers35}{[O-R] Prefers work that is routine}
#'   \item{pers36}{[E] Is outgoing, sociable}
#'   \item{pers37}{[A-R] Is sometimes rude to others}
#'   \item{pers38}{[C] Makes plans and follows through with them}
#'   \item{pers39}{[N] Gets nervous easily}
#'   \item{pers40}{[O] Likes to reflect, play with ideas}
#'   \item{pers41}{[O-R] Has few artistic interests}
#'   \item{pers42}{[A] Likes to cooperate with others}
#'   \item{pers43}{[C-R] Is easily distracted}
#'   \item{pers44}{[O] Is sophisticated in art, music, or literature}
#' }
#' @references John, O. P., & Srivastava, S. (1999). The Big Five trait taxonomy:
#'   History, measurement, and theoretical perspectives. In L. A. Pervin & O. P.
#'   John (Eds.), \emph{Handbook of personality: Theory and research} (2nd ed.,
#'   pp. 102-138). Guilford Press.
#' @examples
#' data(df_personality)
#' head(df_personality)
"df_personality"

#' Titanic Dataset
#'
#' A dataset containing information about passengers on the Titanic.
#'
#' @format A data frame with the following variables:
#' \describe{
#'   \item{PassengerId}{Unique identifier for each passenger}
#'   \item{survived}{Survival status (0=No, 1=Yes)}
#'   \item{pclass}{Passenger class (1=1st, 2=2nd, 3=3rd)}
#'   \item{name}{Name of the passenger}
#'   \item{sex}{Gender of the passenger}
#'   \item{age}{Age of the passenger}
#'   \item{sibsp}{Number of siblings/spouses aboard the Titanic}
#'   \item{parch}{Number of parents/children aboard the Titanic}
#'   \item{ticket}{Ticket number}
#'   \item{fare}{Passenger fare}
#'   \item{cabin}{Cabin number}
#'   \item{embarked}{Port of embarkation (C=Cherbourg; Q=Queenstown; S=Southampton)}
#'   \item{boat}{Lifeboat number}
#'   \item{body}{Body number}
#'   \item{home.dest}{Home destination}
#' }
#' @examples
#' data(df_titanic)
#' head(df_titanic)
"df_titanic"

#' Carbon Dioxide Uptake in Grass Plants
#'
#' The CO2 data frame has 84 rows and 5 columns of data from an experiment on the cold tolerance of the grass species Echinochloa crus-galli.
#'
#' @format A data frame with 84 rows and 5 variables:
#' \describe{
#'   \item{Plant}{an ordered factor with levels Qn1 < Qn2 < Qn3 < ... < Mc1 giving a unique identifier for each plant). Used as a grouping factor.}
#'   \item{Type}{a factor with levels Quebec Mississippi giving the origin of the plant}
#'   \item{Treatment}{a factor with levels nonchilled chilled}
#'   \item{conc}{a numeric vector of ambient carbon dioxide concentrations (mL/L)}
#'   \item{uptake}{a numeric vector of carbon dioxide uptake rates (in \eqn{\mu}mol/m²/sec)}
#' }
#'
#' @details
#' Grouped formulas like \code{uptake ~ conc | Plant} are useful in lattice graphics
#' and mixed-effect models. The vertical bar (`|`) separates the grouping variable.
#' This allows modeling or plotting the response (\code{uptake}) versus the predictor
#' (\code{conc}) within each level of \code{Plant}.
#' 
#' @source
#' Potvin, C., Lechowicz, M. J. and Tardif, S. (1990) “The statistical analysis of ecophysiological response curves obtained from experiments involving repeated measures”, Ecology, 71, 1389–1400.
#' Pinheiro, J. C. and Bates, D. M. (2000) Mixed-effects Models in S and S-PLUS, Springer.
#' @examples
#' data(df_co2)
#' head(df_co2)

"df_co2"

#' Big Five Personality Test Dataset
#'
#' This dataset contains responses to an interactive online Big Five personality test
#' conducted around 2012. Participants rated themselves on 50 personality statements,
#' and also provided demographic and technical metadata. Responses were collected
#' with informed consent, and missing data is coded as 0.
#'
#' @format A data frame with 19719 rows and 57 variables:
#' \describe{
#'   \item{race}{Race/ethnic background (1–13, 0=missing)}
#'   \item{age}{Age (integer; only responses from participants 13 and older included)}
#'   \item{engnat}{Is English your native language? (1=Yes, 2=No, 0=missing)}
#'   \item{gender}{1=Male, 2=Female, 3=Other, 0=missing}
#'   \item{hand}{Dominant writing hand: 1=Right, 2=Left, 3=Both, 0=missing}
#'   \item{source}{How participant came to the test site: 
#'     1=Internal link,
#'     2=Google,
#'     3=Facebook,
#'     4=.edu site,
#'     6=Other/unknown}
#'   \item{country}{Two-letter ISO country code (e.g., "US", "GB")}
#'   \item{E1}{I am the life of the party.}
#'   \item{E2}{I don't talk a lot.}
#'   \item{E3}{I feel comfortable around people.}
#'   \item{E4}{I keep in the background.}
#'   \item{E5}{I start conversations.}
#'   \item{E6}{I have little to say.}
#'   \item{E7}{I talk to a lot of different people at parties.}
#'   \item{E8}{I don't like to draw attention to myself.}
#'   \item{E9}{I don't mind being the center of attention.}
#'   \item{E10}{I am quiet around strangers.}
#'   \item{N1}{I get stressed out easily.}
#'   \item{N2}{I am relaxed most of the time.}
#'   \item{N3}{I worry about things.}
#'   \item{N4}{I seldom feel blue.}
#'   \item{N5}{I am easily disturbed.}
#'   \item{N6}{I get upset easily.}
#'   \item{N7}{I change my mood a lot.}
#'   \item{N8}{I have frequent mood swings.}
#'   \item{N9}{I get irritated easily.}
#'   \item{N10}{I often feel blue.}
#'   \item{A1}{I feel little concern for others.}
#'   \item{A2}{I am interested in people.}
#'   \item{A3}{I insult people.}
#'   \item{A4}{I sympathize with others' feelings.}
#'   \item{A5}{I am not interested in other people's problems.}
#'   \item{A6}{I have a soft heart.}
#'   \item{A7}{I am not really interested in others.}
#'   \item{A8}{I take time out for others.}
#'   \item{A9}{I feel others' emotions.}
#'   \item{A10}{I make people feel at ease.}
#'   \item{C1}{I am always prepared.}
#'   \item{C2}{I leave my belongings around.}
#'   \item{C3}{I pay attention to details.}
#'   \item{C4}{I make a mess of things.}
#'   \item{C5}{I get chores done right away.}
#'   \item{C6}{I often forget to put things back in their proper place.}
#'   \item{C7}{I like order.}
#'   \item{C8}{I shirk my duties.}
#'   \item{C9}{I follow a schedule.}
#'   \item{C10}{I am exacting in my work.}
#'   \item{O1}{I have a rich vocabulary.}
#'   \item{O2}{I have difficulty understanding abstract ideas.}
#'   \item{O3}{I have a vivid imagination.}
#'   \item{O4}{I am not interested in abstract ideas.}
#'   \item{O5}{I have excellent ideas.}
#'   \item{O6}{I do not have a good imagination.}
#'   \item{O7}{I am quick to understand things.}
#'   \item{O8}{I use difficult words.}
#'   \item{O9}{I spend time reflecting on things.}
#'   \item{O10}{I am full of ideas.}
#' }
#'
#' @details
#' Personality items were rated on a five-point Likert scale: #' 1=Disagree, 3=Neutral, 5=Agree. Missed=0.
#' 
#' \strong{race} Chosen from a drop down menu. 1=Mixed Race, 2=Arctic (Siberian, Eskimo), 3=Caucasian (European), 4=Caucasian (Indian), 5=Caucasian (Middle East), 6=Caucasian (North African, Other), 7=Indigenous Australian, 8=Native American, 9=North East Asian (Mongol, Tibetan, Korean Japanese, etc), 10=Pacific (Polynesian, Micronesian, etc), 11=South East Asian (Chinese, Thai, Malay, Filipino, etc), 12=West African, Bushmen, Ethiopian, 13=Other (0=missed)
#' \strong{age}	Entered as text (individuals reporting age < 13 were not recorded)
#' \strong{engnat}	Response to "is English your native language?". 1=Yes, 2=No (0=missed)
#' \strong{gender}	Chosen from a drop down menu. 1=Male, 2=Female, 3=Other (0=missed)
#' \strong{hand}	"What hand do you use to write with?". 1=Right, 2=Left, 3=Both (0=missed)
#' 
#' On this page users were also asked to confirm that their answers were accurate and could be used for research. Participants who did not were not recorded). Some values were calculated from technical information.
#' 
#' \strong{country}	The participant's technical location. ISO country code.
#' \strong{source}	How the participant came to the test. Based on HTTP Referrer. 1=from another page on the test website, 2=from google, 3=from facebook, 4=from any url with ".edu" in its domain name (e.g. xxx.edu, xxx.edu.au), 6=other source, or HTTP Referer not provided.
#' 
#' In psychological trait theory, the Big Five personality traits, also known as the five-factor model (FFM) and the OCEAN model, is a suggested taxonomy, or grouping, for personality traits, developed from the 1980s onwards. When factor analysis (a statistical technique) is applied to personality survey data, some words used to describe aspects of personality are often applied to the same person. For example, someone described as conscientious is more likely to be described as "always prepared" rather than "messy". This theory is based therefore on semantic associations between words and not on neuropsychological experiments. This theory uses descriptors of common language and suggests five broad dimensions commonly used to describe the human personality and psyche.
#' 
#' The theory identifies five factors:
#' \itemize{
#'   \item \strong{Openness to experience (O)} (inventive/curious vs. consistent/cautious)
#'   \item \strong{Conscientiousness (C)} (efficient/organized vs. extravagant/careless)
#'   \item \strong{Extraversion (E)} (outgoing/energetic vs. solitary/reserved)
#'   \item \strong{Agreeableness (A)} (friendly/compassionate vs. challenging/callous)
#'   \item \strong{Neuroticism (N)} (sensitive/nervous vs. resilient/confident)
#' }
#' The five factors are represented using the acronyms OCEAN or CANOE. Beneath each proposed global factor, there are a number of correlated and more specific primary factors. For example, extroversion is typically associated with qualities such as gregariousness, assertiveness, excitement-seeking, warmth, activity, and positive emotions.  
#' Family life and the way someone was raised will affect these traits. Twin studies and other research have shown that about half of the variation between individuals results from their genetics and half from their environments. Researchers have found conscientiousness, extroversion, openness to experience, and neuroticism to be relatively stable from childhood through adulthood.
#' 
#' Items are grouped by Big Five traits:
#' \itemize{
#'   \item \strong{Extraversion (E)}: E1 to E10
#'   \item \strong{Neuroticism (N)}: N1 to N10
#'   \item \strong{Agreeableness (A)}: A1 to A10
#'   \item \strong{Conscientiousness (C)}: C1 to C10
#'   \item \strong{Openness (O)}: O1 to O10
#' }
#'
#' Negatively keyed items are: E2, E4, E6, E8, E10, N2, N4, A1, A3, A5, A7, C2, C4, C6, C8, O2, O4, O6.
#' These should be reverse-coded prior to scoring.
#'
#' @source
#' Collected via an online personality test with informed consent (~2012).
#' Downloaded from Kaggle.com by the user Lucas Greenwell. see \url{https://www.kaggle.com/datasets/lucasgreenwell/ocean-five-factor-personality-test-responses}
#' 
#' @examples
#' data(df_ocean)
#' head(df_ocean)
#' 
#' # Compute Big Five average scores (after reverse scoring)
#' # library(dplyr)
#' # df_ocean <- df_ocean %>% mutate(E=rowMeans(select(., E1:E10), na.rm=TRUE))
#'
"df_ocean"

#' Young People Survey Responses
#'
#' Survey responses from 1010 young people (15-30 years old) on music preferences,
#' movie preferences, hobbies, phobias, health habits, personality traits,
#' spending habits, and demographics.
#'
#' @format A data frame with 1010 rows and 151 variables. All preference and
#'   personality items are rated on a 1-5 Likert scale (1=strongly disagree /
#'   not interested, 5=strongly agree / very interested) unless otherwise noted.
#' \itemize{
#'   \item \strong{Participant Number}: Unique participant identifier
#'   \item \strong{Music}: Interest in music generally
#'   \item \strong{Slow songs or fast songs}: Preference for slow vs fast songs
#'   \item \strong{Dance}: Interest in dance music
#'   \item \strong{Folk}: Interest in folk music
#'   \item \strong{Country}: Interest in country music
#'   \item \strong{Classical music}: Interest in classical music
#'   \item \strong{Musical}: Interest in musicals
#'   \item \strong{Pop}: Interest in pop music
#'   \item \strong{Rock}: Interest in rock music
#'   \item \strong{Metal or Hardrock}: Interest in metal/hardrock
#'   \item \strong{Punk}: Interest in punk music
#'   \item \strong{Hiphop, Rap}: Interest in hiphop/rap
#'   \item \strong{Reggae, Ska}: Interest in reggae/ska
#'   \item \strong{Swing, Jazz}: Interest in swing/jazz
#'   \item \strong{Rock n roll}: Interest in rock n roll
#'   \item \strong{Alternative}: Interest in alternative music
#'   \item \strong{Latino}: Interest in Latino music
#'   \item \strong{Techno, Trance}: Interest in techno/trance
#'   \item \strong{Opera}: Interest in opera
#'   \item \strong{Movies}: Interest in movies generally
#'   \item \strong{Horror}: Interest in horror films
#'   \item \strong{Thriller}: Interest in thrillers
#'   \item \strong{Comedy}: Interest in comedy films
#'   \item \strong{Romantic}: Interest in romantic films
#'   \item \strong{Sci-fi}: Interest in sci-fi films
#'   \item \strong{War}: Interest in war films
#'   \item \strong{Fantasy/Fairy tales}: Interest in fantasy films
#'   \item \strong{Animated}: Interest in animated films
#'   \item \strong{Documentary}: Interest in documentaries
#'   \item \strong{Western}: Interest in westerns
#'   \item \strong{Action}: Interest in action films
#'   \item \strong{History}: Interest in history
#'   \item \strong{Psychology}: Interest in psychology
#'   \item \strong{Politics}: Interest in politics
#'   \item \strong{Mathematics}: Interest in mathematics
#'   \item \strong{Physics}: Interest in physics
#'   \item \strong{Internet}: Interest in internet
#'   \item \strong{PC}: Interest in computers
#'   \item \strong{Economy Management}: Interest in economy/management
#'   \item \strong{Biology}: Interest in biology
#'   \item \strong{Chemistry}: Interest in chemistry
#'   \item \strong{Reading}: Interest in reading
#'   \item \strong{Geography}: Interest in geography
#'   \item \strong{Foreign languages}: Interest in foreign languages
#'   \item \strong{Medicine}: Interest in medicine
#'   \item \strong{Law}: Interest in law
#'   \item \strong{Cars}: Interest in cars
#'   \item \strong{Art exhibitions}: Interest in art exhibitions
#'   \item \strong{Religion}: Interest in religion
#'   \item \strong{Countryside, outdoors}: Interest in countryside/outdoors
#'   \item \strong{Dancing}: Interest in dancing
#'   \item \strong{Musical instruments}: Interest in playing musical instruments
#'   \item \strong{Writing}: Interest in writing
#'   \item \strong{Passive sport}: Interest in watching sports
#'   \item \strong{Active sport}: Interest in playing sports
#'   \item \strong{Gardening}: Interest in gardening
#'   \item \strong{Celebrities}: Interest in celebrities
#'   \item \strong{Shopping}: Interest in shopping
#'   \item \strong{Science and technology}: Interest in science and technology
#'   \item \strong{Theatre}: Interest in theatre
#'   \item \strong{Fun with friends}: Enjoyment of socialising with friends
#'   \item \strong{Adrenaline sports}: Interest in adrenaline sports
#'   \item \strong{Pets}: Interest in pets
#'   \item \strong{Flying}: Fear of flying
#'   \item \strong{Storm}: Fear of storms
#'   \item \strong{Darkness}: Fear of darkness
#'   \item \strong{Heights}: Fear of heights
#'   \item \strong{Spiders}: Fear of spiders
#'   \item \strong{Snakes}: Fear of snakes
#'   \item \strong{Rats}: Fear of rats
#'   \item \strong{Ageing}: Fear of ageing
#'   \item \strong{Dangerous dogs}: Fear of dangerous dogs
#'   \item \strong{Fear of public speaking}: Fear of public speaking
#'   \item \strong{Smoking}: Smoking behaviour/attitude
#'   \item \strong{Alcohol}: Alcohol consumption/attitude
#'   \item \strong{Healthy eating}: Attitude toward healthy eating
#'   \item \strong{Daily events}: Attitude toward planning daily events
#'   \item \strong{Prioritising workload}: Ability to prioritise workload
#'   \item \strong{Writing notes}: Habit of writing notes
#'   \item \strong{Workaholism}: Tendency toward workaholism
#'   \item \strong{Thinking ahead}: Tendency to think ahead
#'   \item \strong{Final judgement}: Tendency to make final judgements
#'   \item \strong{Reliability}: Self-rated reliability
#'   \item \strong{Keeping promises}: Tendency to keep promises
#'   \item \strong{Loss of interest}: Tendency to lose interest
#'   \item \strong{Friends versus money}: Attitude toward friends vs money
#'   \item \strong{Funniness}: Self-rated funniness
#'   \item \strong{Fake}: Tendency to be fake
#'   \item \strong{Criminal damage}: Attitude toward criminal damage
#'   \item \strong{Decision making}: Decision-making style
#'   \item \strong{Elections}: Attitude toward elections
#'   \item \strong{Self-criticism}: Tendency toward self-criticism
#'   \item \strong{Judgment calls}: Tendency to make judgment calls
#'   \item \strong{Hypochondria}: Tendency toward hypochondria
#'   \item \strong{Empathy}: Level of empathy
#'   \item \strong{Eating to survive}: Attitude toward eating
#'   \item \strong{Giving}: Tendency to give to others
#'   \item \strong{Compassion to animals}: Compassion toward animals
#'   \item \strong{Borrowed stuff}: Attitude toward returning borrowed items
#'   \item \strong{Loneliness}: Tendency to feel lonely
#'   \item \strong{Cheating in school}: Attitude toward cheating
#'   \item \strong{Health}: Self-rated health
#'   \item \strong{Changing the past}: Desire to change the past
#'   \item \strong{God}: Belief in God
#'   \item \strong{Dreams}: Belief in dreams
#'   \item \strong{Charity}: Attitude toward charity
#'   \item \strong{Number of friends}: Number of friends
#'   \item \strong{Punctuality}: Self-rated punctuality
#'   \item \strong{Lying}: Tendency to lie
#'   \item \strong{Waiting}: Attitude toward waiting
#'   \item \strong{New environment}: Comfort in new environments
#'   \item \strong{Mood swings}: Tendency to have mood swings
#'   \item \strong{Appearence and gestures}: Attention to appearance and gestures
#'   \item \strong{Socializing}: Enjoyment of socializing
#'   \item \strong{Achievements}: Drive for achievements
#'   \item \strong{Responding to a serious letter}: Tendency to respond to serious letters
#'   \item \strong{Children}: Attitude toward children
#'   \item \strong{Assertiveness}: Level of assertiveness
#'   \item \strong{Getting angry}: Tendency to get angry
#'   \item \strong{Knowing the right people}: Value placed on knowing the right people
#'   \item \strong{Public speaking}: Comfort with public speaking
#'   \item \strong{Unpopularity}: Attitude toward unpopularity
#'   \item \strong{Life struggles}: Attitude toward life struggles
#'   \item \strong{Happiness in life}: Self-rated happiness
#'   \item \strong{Energy levels}: Self-rated energy levels
#'   \item \strong{Small - big dogs}: Preference for small vs big dogs
#'   \item \strong{Personality}: Self-rated personality
#'   \item \strong{Finding lost valuables}: Tendency to return lost valuables
#'   \item \strong{Getting up}: Ease of getting up in the morning
#'   \item \strong{Interests or hobbies}: Number of interests or hobbies
#'   \item \strong{Parents' advice}: Attitude toward parents' advice
#'   \item \strong{Questionnaires or polls}: Attitude toward questionnaires
#'   \item \strong{Internet usage}: Hours of internet usage
#'   \item \strong{Finances}: Self-rated financial management
#'   \item \strong{Shopping centres}: Attitude toward shopping centres
#'   \item \strong{Branded clothing}: Attitude toward branded clothing
#'   \item \strong{Entertainment spending}: Spending on entertainment
#'   \item \strong{Spending on looks}: Spending on looks
#'   \item \strong{Spending on gadgets}: Spending on gadgets
#'   \item \strong{Spending on healthy eating}: Spending on healthy eating
#'   \item \strong{Age}: Age in years
#'   \item \strong{Height}: Height in cm
#'   \item \strong{Weight}: Weight in kg
#'   \item \strong{Number of siblings}: Number of siblings
#'   \item \strong{Gender}: 1=Female, 2=Male
#'   \item \strong{Left - right handed}: 1=Right, 2=Left
#'   \item \strong{Education}: 1=Primary, 2=Secondary, 3=College/University, 4=Masters, 5=Doctorate
#'   \item \strong{Only child}: 1=Yes, 2=No
#'   \item \strong{Village - town}: 1=Village, 2=City
#'   \item \strong{House - block of flats}: 1=House, 2=Block of flats
#' }
#' @source Collected from students of Statistics at FSEV UK. Available on Kaggle.
#' @examples
#' data(df_responses)
#' head(df_responses)
"df_responses"
